using System.Collections.Generic;
using System.Text;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class ClientPrefixEmitter
{
    private const string AtpClientType = "global::BlueBlaze.Client.Core.IAtProtocolClient";

    internal static void Emit(
        string[] prefixSegments,
        string clientCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var n = prefixSegments.Length;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine($"namespace {clientCodeNamespace};");
        sb.AppendLine();
        sb.AppendLine("public static partial class AtProtocolClientExtensions");
        sb.AppendLine("{");

        var currentStructName = ConcatSegments(prefixSegments, n);
        var fullStructType = BuildFullStructType(prefixSegments, clientCodeNamespace);
        var propertyName = prefixSegments[n - 1];

        if (n == 1)
        {
            sb.AppendLine($"    extension ({AtpClientType} client)");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {fullStructType} {propertyName} => new(client);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public readonly partial struct {currentStructName}({AtpClientType} client);");
        }
        else
        {
            for (var i = 0; i < n - 1; i++)
            {
                var indent = new string(' ', (i + 1) * 4);
                var parentStructName = ConcatSegments(prefixSegments, i + 1);
                sb.AppendLine($"{indent}public readonly partial struct {parentStructName}");
                sb.AppendLine($"{indent}{{");
            }

            var innerIndent = new string(' ', n * 4);
            sb.AppendLine($"{innerIndent}public {fullStructType} {propertyName} => new(client);");
            sb.AppendLine();
            sb.AppendLine($"{innerIndent}public readonly partial struct {currentStructName}({AtpClientType} client);");

            for (var i = n - 2; i >= 0; i--)
            {
                var closingIndent = new string(' ', (i + 1) * 4);
                sb.AppendLine($"{closingIndent}}}");
            }
        }

        sb.AppendLine("}");

        var prefixDot = string.Join(".", prefixSegments);
        var hintName = LexiconNameHelper.GetHintNameBase(clientCodeNamespace, "Prefix." + prefixDot) + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, sb.ToString()));
    }

    // 先頭 count 個のセグメントを結合: ["Com","Atproto","Server"], 2 -> "ComAtproto"
    internal static string ConcatSegments(string[] segments, int count)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < count; i++)
        {
            sb.Append(segments[i]);
        }

        return sb.ToString();
    }

    // プレフィックスに対応する global:: 修飾の完全型名を構築
    // ["Com","Atproto"] -> "global::{ns}.AtProtocolClientExtensions.Com.ComAtproto"
    private static string BuildFullStructType(string[] segments, string ns)
    {
        var sb = new StringBuilder($"global::{ns}.AtProtocolClientExtensions");
        for (var i = 1; i <= segments.Length; i++)
        {
            sb.Append('.');
            sb.Append(ConcatSegments(segments, i));
        }

        return sb.ToString();
    }
}
