using System.Collections.Generic;
using System.Text;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class ClientPrefixEmitter
{
    private const string AtpClientType = "global::BlueBlaze.Core.IAtProtocolClient";

    internal static void Emit(
        string[] prefixSegments,
        string clientCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var n = prefixSegments.Length;
        var isb = new IndentedStringBuilder();

        isb.AppendLine("// <auto-generated/>");
        isb.AppendLine("#nullable enable");
        isb.AppendLine("#pragma warning disable CS1591");
        isb.AppendLine();
        isb.AppendLine($"namespace {clientCodeNamespace};");
        isb.AppendLine();
        isb.AppendLine("public static partial class AtProtocolClientExtensions");
        isb.AppendLine("{");
        using (isb.Indent())
        {
            var currentStructName = ConcatSegments(prefixSegments, n);
            var fullStructType = BuildFullStructType(prefixSegments, clientCodeNamespace);
            var propertyName = prefixSegments[n - 1];

            if (n == 1)
            {
                isb.AppendLine($"extension ({AtpClientType} client)");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine($"public {fullStructType} {propertyName} => new(client);");
                }
                isb.AppendLine("}");
                isb.AppendLine();
                isb.AppendLine($"public readonly partial struct {currentStructName}({AtpClientType} client);");
            }
            else
            {
                for (var i = 0; i < n - 1; i++)
                {
                    var parentStructName = ConcatSegments(prefixSegments, i + 1);
                    isb.AppendLine($"public readonly partial struct {parentStructName}");
                    isb.AppendLine("{");
                    isb.Indent();
                }

                isb.AppendLine($"public {fullStructType} {propertyName} => new(client);");
                isb.AppendLine();
                isb.AppendLine($"public readonly partial struct {currentStructName}({AtpClientType} client);");

                for (var i = n - 2; i >= 0; i--)
                {
                    isb.Dedent();
                    isb.AppendLine("}");
                }
            }
        }
        isb.AppendLine("}");

        var prefixDot = string.Join(".", prefixSegments);
        var hintName = LexiconNameHelper.GetHintNameBase(clientCodeNamespace, "Prefix." + prefixDot) + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, isb.ToString()));
    }

    // 先頭 count 個のセグメントを結合: ["Com","Atproto","Server"], 2 -> "ComAtproto"
    internal static string ConcatSegments(string[] segments, int count)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < count; i++)
        {
            sb.Append(segments[i]);
        }

        return sb.ToString();
    }

    // プレフィックスに対応する global:: 修飾の完全型名を構築
    // ["Com","Atproto"] -> "global::{ns}.AtProtocolClientExtensions.Com.ComAtproto"
    private static string BuildFullStructType(string[] segments, string ns)
    {
        var sb = new StringBuilder($"global::{ns}.AtProtocolClientExtensions");
        for (var i = 1; i <= segments.Length; i++)
        {
            sb.Append('.');
            sb.Append(ConcatSegments(segments, i));
        }

        return sb.ToString();
    }
}
