using System;
using System.Collections.Generic;
using System.Text;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class ClientMethodEmitter
{
    private const string CoreNs = "global::BlueBlaze.Client.Core";

    internal static void Emit(
        LexiconDocumentWithInfo docInfo,
        string generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var doc = docInfo.Document;
        var nsid = doc.Id;

        if (!doc.Definitions.TryGetValue("main", out var mainDef))
        {
            return;
        }

        if (mainDef is QueryDefinition queryDef)
        {
            EmitMethod(nsid,
                hasParameters: queryDef.Parameters?.Properties?.Count > 0,
                hasInput: false,
                hasOutput: queryDef.Output?.Schema is ObjectDefinition,
                generatedCodeNamespace, files);
        }
        else if (mainDef is ProcedureDefinition procDef)
        {
            EmitMethod(nsid,
                hasParameters: false,
                hasInput: procDef.Input?.Schema is ObjectDefinition,
                hasOutput: procDef.Output?.Schema is ObjectDefinition,
                generatedCodeNamespace, files);
        }
    }

    private static void EmitMethod(
        string nsid,
        bool hasParameters,
        bool hasInput,
        bool hasOutput,
        string generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var segments = LexiconNameHelper.NsidToSegments(nsid);
        var containerSegments = new string[segments.Length - 1];
        Array.Copy(segments, containerSegments, segments.Length - 1);

        var methodName = segments[segments.Length - 1] + "Async";
        var modelPath = string.Join(".", segments);
        var modelType = $"global::{generatedCodeNamespace}.{modelPath}";

        var outputType = hasOutput
            ? $"{modelType}.Output"
            : $"{CoreNs}.VoidOutput";

        var returnType = $"global::System.Threading.Tasks.ValueTask<{CoreNs}.LexiconResponse<{outputType}>>";

        var requestExpr = hasInput
            ? $"new {modelType}.Request(input)"
            : hasParameters
                ? $"new {modelType}.Request(parameters)"
                : $"{modelType}.Request.Instance";

        var deserializerExpr = hasOutput
            ? $"{modelType}.Deserializer.Instance"
            : $"{CoreNs}.VoidOutputDeserializer.Instance";

        var sb = new StringBuilder();
        EmitFileHeader(sb, generatedCodeNamespace);

        sb.AppendLine("public static partial class AtProtocolClientExtensions");
        sb.AppendLine("{");

        OpenPartialStructContainers(sb, containerSegments);

        var methodIndent = new string(' ', (containerSegments.Length + 1) * 4);
        var callIndent = methodIndent + "    ";

        sb.Append($"{methodIndent}public {returnType} {methodName}(");

        if (hasInput)
        {
            sb.AppendLine();
            sb.Append($"{callIndent}{modelType}.Input input,");
        }
        else if (hasParameters)
        {
            sb.AppendLine();
            sb.Append($"{callIndent}{modelType}.Parameters? parameters = null,");
        }

        if (hasInput || hasParameters)
        {
            sb.AppendLine();
            sb.Append($"{callIndent}");
        }

        sb.AppendLine($"global::System.Threading.CancellationToken cancellationToken = default) =>");
        sb.AppendLine($"{callIndent}client.SendAsync(");
        sb.AppendLine($"{callIndent}    {requestExpr},");
        sb.AppendLine($"{callIndent}    {deserializerExpr},");
        sb.AppendLine($"{callIndent}    cancellationToken);");

        ClosePartialStructContainers(sb, containerSegments);
        sb.AppendLine("}");

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, modelPath + ".Client") + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, sb.ToString()));
    }

    private static void EmitFileHeader(StringBuilder sb, string generatedCodeNamespace)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine($"namespace {generatedCodeNamespace};");
        sb.AppendLine();
    }

    private static void OpenPartialStructContainers(StringBuilder sb, string[] containerSegments)
    {
        for (var i = 0; i < containerSegments.Length; i++)
        {
            var indent = new string(' ', (i + 1) * 4);
            var structName = ClientPrefixEmitter.ConcatSegments(containerSegments, i + 1);
            sb.AppendLine($"{indent}public readonly partial struct {structName}");
            sb.AppendLine($"{indent}{{");
        }
    }

    private static void ClosePartialStructContainers(StringBuilder sb, string[] containerSegments)
    {
        for (var i = containerSegments.Length - 1; i >= 0; i--)
        {
            var indent = new string(' ', (i + 1) * 4);
            sb.AppendLine($"{indent}}}");
        }
    }
}
