using System.Collections.Generic;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class DeserializerEmitter
{
    private const string ClientCoreNamespace = "global::BlueBlaze.Client.Core";

    internal static void Emit(
        string[] segments,
        bool generateTypeInfo,
        string? generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var modelPath = string.Join(".", segments);
        const string ClassName = "Deserializer";
        var classPath = modelPath + "." + ClassName;
        var outputType = GlobalType(generatedCodeNamespace, modelPath + ".Output");

        var isb = new IndentedStringBuilder();
        isb.AppendLine("// <auto-generated/>");
        isb.AppendLine("#nullable enable");
        isb.AppendLine();
        if (!string.IsNullOrEmpty(generatedCodeNamespace))
        {
            isb.AppendLine($"namespace {generatedCodeNamespace};");
            isb.AppendLine();
        }

        OpenSealedContainers(isb, segments);

        isb.AppendLine($"public sealed class {ClassName} : {ClientCoreNamespace}.IResponseDeserializer<{outputType}>");
        isb.AppendLine("{");
        using (isb.Indent())
        {
            isb.AppendLine($"public static readonly {ClassName} Instance = new();");
            isb.AppendLine();
            isb.AppendLine($"private {ClassName}() {{ }}");
            isb.AppendLine();

            if (generateTypeInfo)
            {
                var typeInfoPropName = BuildTypeInfoPropertyName(segments);
                var contextType = GlobalType(generatedCodeNamespace, "LexiconJsonSerializerContext");
                isb.AppendLine($"public global::System.Threading.Tasks.ValueTask<{outputType}> DeserializeAsync(");
                using (isb.Indent())
                {
                    isb.AppendLine("global::System.Net.Http.HttpContent content,");
                    isb.AppendLine("global::System.Threading.CancellationToken cancellationToken = default) =>");
                    isb.AppendLine($"new global::System.Threading.Tasks.ValueTask<{outputType}>(");
                    using (isb.Indent())
                    {
                        isb.AppendLine("global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync(");
                        using (isb.Indent())
                        {
                            isb.AppendLine($"content, {contextType}.Default.{typeInfoPropName}, cancellationToken));");
                        }
                    }
                }
            }
            else
            {
                isb.AppendLine($"public async global::System.Threading.Tasks.ValueTask<{outputType}> DeserializeAsync(");
                using (isb.Indent())
                {
                    isb.AppendLine("global::System.Net.Http.HttpContent content,");
                    isb.AppendLine("global::System.Threading.CancellationToken cancellationToken = default)");
                }
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine("var result = await global::System.Net.Http.Json.HttpContentJsonExtensions");
                    using (isb.Indent())
                    {
                        isb.AppendLine($".ReadFromJsonAsync<{outputType}>(content, cancellationToken)");
                        isb.AppendLine(".ConfigureAwait(false);");
                    }
                    isb.AppendLine("return result!;");
                }
                isb.AppendLine("}");
            }
        }
        isb.AppendLine("}");

        CloseContainers(isb, segments.Length);

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, classPath) + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, isb.ToString()));
    }

    // All segments joined PascalCase + "Output" → unique property name for [JsonSerializable]
    private static string BuildTypeInfoPropertyName(string[] segments)
    {
        return string.Concat(segments) + "Output";
    }

    private static string GlobalType(string? ns, string typePath)
    {
        return string.IsNullOrEmpty(ns) ? $"global::{typePath}" : $"global::{ns}.{typePath}";
    }

    private static void OpenSealedContainers(IndentedStringBuilder isb, string[] segments)
    {
        for (var i = 0; i < segments.Length; i++)
        {
            isb.AppendLine($"public sealed partial class {segments[i]}");
            isb.AppendLine("{");
            isb.Indent();
        }
    }

    private static void CloseContainers(IndentedStringBuilder isb, int count)
    {
        for (var i = count - 1; i >= 0; i--)
        {
            isb.Dedent();
            isb.AppendLine("}");
        }
    }
}
