using System.Collections.Generic;
using System.Text;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class DeserializerEmitter
{
    private const string ClientCoreNamespace = "global::BlueBlaze.Client.Core";

    internal static void Emit(
        string[] segments,
        bool generateTypeInfo,
        string? generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var modelPath = string.Join(".", segments);
        const string ClassName = "Deserializer";
        var classPath = modelPath + "." + ClassName;
        var outputType = GlobalType(generatedCodeNamespace, modelPath + ".Output");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(generatedCodeNamespace))
        {
            sb.AppendLine($"namespace {generatedCodeNamespace};");
            sb.AppendLine();
        }

        OpenSealedContainers(sb, segments);

        var indent = new string(' ', segments.Length * 4);
        var indent1 = new string(' ', (segments.Length + 1) * 4);

        sb.AppendLine($"{indent}public sealed class {ClassName} : {ClientCoreNamespace}.IResponseDeserializer<{outputType}>");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent1}public static readonly {ClassName} Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"{indent1}private {ClassName}() {{ }}");
        sb.AppendLine();

        if (generateTypeInfo)
        {
            var typeInfoPropName = BuildTypeInfoPropertyName(segments);
            var contextType = GlobalType(generatedCodeNamespace, "LexiconJsonSerializerContext");
            sb.AppendLine($"{indent1}public global::System.Threading.Tasks.ValueTask<{outputType}> DeserializeAsync(");
            sb.AppendLine($"{indent1}    global::System.Net.Http.HttpContent content,");
            sb.AppendLine($"{indent1}    global::System.Threading.CancellationToken cancellationToken = default) =>");
            sb.AppendLine($"{indent1}    new global::System.Threading.Tasks.ValueTask<{outputType}>(");
            sb.AppendLine($"{indent1}        global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync(");
            sb.AppendLine($"{indent1}            content, {contextType}.Default.{typeInfoPropName}, cancellationToken));");
        }
        else
        {
            sb.AppendLine($"{indent1}public async global::System.Threading.Tasks.ValueTask<{outputType}> DeserializeAsync(");
            sb.AppendLine($"{indent1}    global::System.Net.Http.HttpContent content,");
            sb.AppendLine($"{indent1}    global::System.Threading.CancellationToken cancellationToken = default)");
            sb.AppendLine($"{indent1}{{");
            sb.AppendLine($"{indent1}    var result = await global::System.Net.Http.Json.HttpContentJsonExtensions");
            sb.AppendLine($"{indent1}        .ReadFromJsonAsync<{outputType}>(content, cancellationToken)");
            sb.AppendLine($"{indent1}        .ConfigureAwait(false);");
            sb.AppendLine($"{indent1}    return result!;");
            sb.AppendLine($"{indent1}}}");
        }

        sb.AppendLine($"{indent}}}");

        CloseContainers(sb, segments.Length);

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, classPath) + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, sb.ToString()));
    }

    // All segments joined PascalCase + "Output" → unique property name for [JsonSerializable]
    private static string BuildTypeInfoPropertyName(string[] segments)
    {
        return string.Concat(segments) + "Output";
    }

    private static string GlobalType(string? ns, string typePath)
    {
        return string.IsNullOrEmpty(ns) ? $"global::{typePath}" : $"global::{ns}.{typePath}";
    }

    private static void OpenSealedContainers(StringBuilder sb, string[] segments)
    {
        for (var i = 0; i < segments.Length; i++)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}public sealed partial class {segments[i]}");
            sb.AppendLine($"{indent}{{");
        }
    }

    private static void CloseContainers(StringBuilder sb, int count)
    {
        for (var i = count - 1; i >= 0; i--)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }
    }
}
