using System.Collections.Generic;
using System.Text;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class InputEmitter
{
    private const string ClientCoreNamespace = "global::BlueBlaze.Client.Core";

    internal static void Emit(
        string nsid,
        string? generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var segments = LexiconNameHelper.NsidToSegments(nsid);
        var modelPath = string.Join(".", segments);
        var className = "Input";
        var classPath = modelPath + "." + className;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(generatedCodeNamespace))
        {
            sb.AppendLine($"namespace {generatedCodeNamespace};");
            sb.AppendLine();
        }

        OpenSealedContainers(sb, segments);

        var indent = new string(' ', segments.Length * 4);
        sb.AppendLine($"{indent}public sealed partial class {className} : {ClientCoreNamespace}.ILexiconInput");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    public global::System.Net.Http.HttpContent ToHttpContent() =>");
        sb.AppendLine($"{indent}        global::System.Net.Http.Json.JsonContent.Create(this, this.GetType());");
        sb.AppendLine($"{indent}}}");

        CloseContainers(sb, segments.Length);

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, classPath + ".ILexiconInput") + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, sb.ToString()));
    }

    private static void OpenSealedContainers(StringBuilder sb, string[] segments)
    {
        for (var i = 0; i < segments.Length; i++)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}public sealed partial class {segments[i]}");
            sb.AppendLine($"{indent}{{");
        }
    }

    private static void CloseContainers(StringBuilder sb, int count)
    {
        for (var i = count - 1; i >= 0; i--)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }
    }
}
