using System.Collections.Generic;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class InputEmitter
{
    private const string ClientCoreNamespace = "global::BlueBlaze.Core";

    internal static void Emit(
        string nsid,
        GeneratorOptions options,
        string? generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var segments = LexiconNameHelper.NsidToSegments(nsid);
        var modelPath = string.Join(".", segments);
        var className = "Input";
        var classPath = modelPath + "." + className;

        var isb = new IndentedStringBuilder();
        isb.AppendLine("// <auto-generated/>");
        isb.AppendLine("#nullable enable");
        isb.AppendLine("#pragma warning disable CS1591");
        isb.AppendLine();
        if (!string.IsNullOrEmpty(generatedCodeNamespace))
        {
            isb.AppendLine($"namespace {generatedCodeNamespace};");
            isb.AppendLine();
        }

        OpenSealedContainers(isb, segments);

        if (options.ShouldEmitAotAttributes)
        {
            isb.AppendLine("[global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(\"JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext.\")]");
            isb.AppendLine("[global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode(\"JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext.\")]");
        }

        isb.AppendLine($"public sealed partial class {className} : {ClientCoreNamespace}.ILexiconInput");
        isb.AppendLine("{");
        using (isb.Indent())
        {
            if (options.GenerateTypeInfo)
            {
                var typeInfoPropName = BuildTypeInfoPropertyName(segments);
                var contextType = GlobalType(generatedCodeNamespace, "LexiconJsonSerializerContext");
                isb.AppendLine("public global::System.Net.Http.HttpContent ToHttpContent()");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine($"return global::System.Net.Http.Json.JsonContent.Create(this, {contextType}.Default.{typeInfoPropName});");
                }
                isb.AppendLine("}");
            }
            else
            {
                isb.AppendLine("public global::System.Net.Http.HttpContent ToHttpContent()");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine("return global::System.Net.Http.Json.JsonContent.Create(this, this.GetType());");
                }
                isb.AppendLine("}");
            }
        }
        isb.AppendLine("}");

        CloseContainers(isb, segments.Length);

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, classPath + ".ILexiconInput") + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, isb.ToString()));
    }

    private static string BuildTypeInfoPropertyName(string[] segments)
    {
        return string.Concat(segments) + "Input";
    }

    private static string GlobalType(string? ns, string typePath)
    {
        return string.IsNullOrEmpty(ns) ? $"global::{typePath}" : $"global::{ns}.{typePath}";
    }

    private static void OpenSealedContainers(IndentedStringBuilder isb, string[] segments)
    {
        for (var i = 0; i < segments.Length; i++)
        {
            isb.AppendLine($"public sealed partial class {segments[i]}");
            isb.AppendLine("{");
            isb.Indent();
        }
    }

    private static void CloseContainers(IndentedStringBuilder isb, int count)
    {
        for (var i = count - 1; i >= 0; i--)
        {
            isb.Dedent();
            isb.AppendLine("}");
        }
    }
}
