using System;
using System.Collections.Generic;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class JsonSerializerContextEmitter
{
    internal static void Emit(
        IReadOnlyList<LexiconDocumentWithInfo> documents,
        string generatedCodeNamespace,
        IReadOnlyDictionary<string, LexiconType?> nsidIndex,
        List<GeneratedSourceFile> files)
    {
        // Phase 1: 登録対象の型を収集（typePath → typeInfoPropName）
        var registeredTypes = BuildRegisteredTypes(documents);

        // Phase 2: [JsonSerializable] 属性を生成
        var isb = new IndentedStringBuilder();
        isb.AppendLine("// <auto-generated/>");
        isb.AppendLine("#nullable enable");
        isb.AppendLine("#pragma warning disable CS1591");
        isb.AppendLine();
        isb.AppendLine($"namespace {generatedCodeNamespace};");
        isb.AppendLine();

        var emittedListTypeInfoNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var docInfo in documents)
        {
            var doc = docInfo.Document;

            if (!doc.Definitions.TryGetValue("main", out var mainDef))
            {
                continue;
            }

            var currentNsid = doc.Id;
            var segments = LexiconNameHelper.NsidToSegments(currentNsid);
            var modelPath = string.Join(".", segments);
            var segmentsConcat = string.Concat(segments);

            if (mainDef is ProcedureDefinition procDef)
            {
                if (procDef.Input?.Schema is ObjectDefinition inputObj)
                {
                    EmitTypeWithUnions(isb, inputObj, $"{modelPath}.Input", $"{segmentsConcat}Input", currentNsid, nsidIndex, registeredTypes, emittedListTypeInfoNames);
                }

                if (procDef.Output?.Schema is ObjectDefinition outputObj)
                {
                    EmitTypeWithUnions(isb, outputObj, $"{modelPath}.Output", $"{segmentsConcat}Output", currentNsid, nsidIndex, registeredTypes, emittedListTypeInfoNames);
                }
            }
            else if (mainDef is QueryDefinition queryDef)
            {
                if (queryDef.Output?.Schema is ObjectDefinition outputObj)
                {
                    EmitTypeWithUnions(isb, outputObj, $"{modelPath}.Output", $"{segmentsConcat}Output", currentNsid, nsidIndex, registeredTypes, emittedListTypeInfoNames);
                }
            }
            else
            {
                continue;
            }

            // サブ定義（query/procedure の Output プレフィックス付き兄弟クラス）
            foreach (var (defKey, def) in doc.Definitions)
            {
                if (defKey == "main")
                {
                    continue;
                }

                if (def is not ObjectDefinition siblingObjDef)
                {
                    continue;
                }

                var siblingClassName = "Output" + LexiconNameHelper.ToPascalCase(defKey);
                EmitTypeWithUnions(isb, siblingObjDef, $"{modelPath}.{siblingClassName}", $"{segmentsConcat}{siblingClassName}", currentNsid, nsidIndex, registeredTypes, emittedListTypeInfoNames);
            }
        }

        isb.AppendLine($"internal sealed partial class LexiconJsonSerializerContext : global::System.Text.Json.Serialization.JsonSerializerContext");
        isb.AppendLine("{");
        isb.AppendLine("}");

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, "LexiconJsonSerializerContext") + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, isb.ToString()));
    }

    private static Dictionary<string, string> BuildRegisteredTypes(IReadOnlyList<LexiconDocumentWithInfo> documents)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var docInfo in documents)
        {
            var doc = docInfo.Document;

            if (!doc.Definitions.TryGetValue("main", out var mainDef))
            {
                continue;
            }

            var segments = LexiconNameHelper.NsidToSegments(doc.Id);
            var modelPath = string.Join(".", segments);
            var segmentsConcat = string.Concat(segments);

            if (mainDef is ProcedureDefinition procDef)
            {
                if (procDef.Input?.Schema is ObjectDefinition)
                {
                    result[$"{modelPath}.Input"] = $"{segmentsConcat}Input";
                }

                if (procDef.Output?.Schema is ObjectDefinition)
                {
                    result[$"{modelPath}.Output"] = $"{segmentsConcat}Output";
                }
            }
            else if (mainDef is QueryDefinition queryDef)
            {
                if (queryDef.Output?.Schema is ObjectDefinition)
                {
                    result[$"{modelPath}.Output"] = $"{segmentsConcat}Output";
                }
            }
            else
            {
                continue;
            }

            foreach (var (defKey, def) in doc.Definitions)
            {
                if (defKey == "main" || def is not ObjectDefinition)
                {
                    continue;
                }

                var siblingClassName = "Output" + LexiconNameHelper.ToPascalCase(defKey);
                result[$"{modelPath}.{siblingClassName}"] = $"{segmentsConcat}{siblingClassName}";
            }
        }

        return result;
    }

    private static void EmitTypeWithUnions(
        IndentedStringBuilder isb,
        ObjectDefinition objDef,
        string typePath,
        string typeInfoPropName,
        string currentNsid,
        IReadOnlyDictionary<string, LexiconType?> nsidIndex,
        IReadOnlyDictionary<string, string> registeredTypes,
        HashSet<string> emittedListTypeInfoNames)
    {
        isb.AppendLine($"[global::System.Text.Json.Serialization.JsonSerializable(typeof({typePath}), TypeInfoPropertyName = \"{typeInfoPropName}\")]");

        foreach (var (propKey, propDef) in objDef.Properties)
        {
            switch (propDef)
            {
                case UnionDefinition:
                {
                    var interfaceName = "I" + LexiconNameHelper.ToPascalCase(propKey);
                    isb.AppendLine($"[global::System.Text.Json.Serialization.JsonSerializable(typeof({typePath}.{interfaceName}), TypeInfoPropertyName = \"{typeInfoPropName}{interfaceName}\")]");
                    break;
                }

                case ArrayDefinition { Items: ReferenceDefinition { Ref: var refStr } }:
                {
                    var itemTypePath = LexiconNameHelper.ResolveRef(currentNsid, refStr, nsidIndex);
                    if (!registeredTypes.TryGetValue(itemTypePath, out var itemTypeInfoPropName))
                    {
                        break;
                    }

                    var listTypeInfoName = "IReadOnlyList" + itemTypeInfoPropName;
                    if (emittedListTypeInfoNames.Add(listTypeInfoName))
                    {
                        isb.AppendLine($"[global::System.Text.Json.Serialization.JsonSerializable(typeof(global::System.Collections.Generic.IReadOnlyList<{itemTypePath}>), TypeInfoPropertyName = \"{listTypeInfoName}\")]");
                    }

                    break;
                }

                default:
                    break;
            }
        }
    }
}
