using System.Collections.Generic;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class JsonSerializerContextEmitter
{
    internal static void Emit(
        IReadOnlyList<LexiconDocumentWithInfo> documents,
        string generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var isb = new IndentedStringBuilder();
        isb.AppendLine("// <auto-generated/>");
        isb.AppendLine("#nullable enable");
        isb.AppendLine("#pragma warning disable CS1591");
        isb.AppendLine();
        isb.AppendLine($"namespace {generatedCodeNamespace};");
        isb.AppendLine();

        foreach (var docInfo in documents)
        {
            var doc = docInfo.Document;

            if (!doc.Definitions.TryGetValue("main", out var mainDef))
            {
                continue;
            }

            var segments = LexiconNameHelper.NsidToSegments(doc.Id);
            var modelPath = string.Join(".", segments);
            var segmentsConcat = string.Concat(segments);

            if (mainDef is ProcedureDefinition procDef)
            {
                if (procDef.Input?.Schema is ObjectDefinition inputObj)
                {
                    EmitTypeWithUnions(isb, inputObj, $"{modelPath}.Input", $"{segmentsConcat}Input");
                }

                if (procDef.Output?.Schema is ObjectDefinition outputObj)
                {
                    EmitTypeWithUnions(isb, outputObj, $"{modelPath}.Output", $"{segmentsConcat}Output");
                }
            }
            else if (mainDef is QueryDefinition queryDef)
            {
                if (queryDef.Output?.Schema is ObjectDefinition outputObj)
                {
                    EmitTypeWithUnions(isb, outputObj, $"{modelPath}.Output", $"{segmentsConcat}Output");
                }
            }
            else
            {
                continue;
            }

            // サブ定義（query/procedure の Output プレフィックス付き兄弟クラス）
            foreach (var (defKey, def) in doc.Definitions)
            {
                if (defKey == "main")
                {
                    continue;
                }

                if (def is not ObjectDefinition siblingObjDef)
                {
                    continue;
                }

                var siblingClassName = "Output" + LexiconNameHelper.ToPascalCase(defKey);
                EmitTypeWithUnions(isb, siblingObjDef, $"{modelPath}.{siblingClassName}", $"{segmentsConcat}{siblingClassName}");
            }
        }

        isb.AppendLine($"internal sealed partial class LexiconJsonSerializerContext : global::System.Text.Json.Serialization.JsonSerializerContext");
        isb.AppendLine("{");
        isb.AppendLine("}");

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, "LexiconJsonSerializerContext") + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, isb.ToString()));
    }

    private static void EmitTypeWithUnions(
        IndentedStringBuilder isb,
        ObjectDefinition objDef,
        string typePath,
        string typeInfoPropName)
    {
        isb.AppendLine($"[global::System.Text.Json.Serialization.JsonSerializable(typeof({typePath}), TypeInfoPropertyName = \"{typeInfoPropName}\")]");

        foreach (var (propKey, propDef) in objDef.Properties)
        {
            if (propDef is not UnionDefinition)
            {
                continue;
            }

            var interfaceName = "I" + LexiconNameHelper.ToPascalCase(propKey);
            isb.AppendLine($"[global::System.Text.Json.Serialization.JsonSerializable(typeof({typePath}.{interfaceName}), TypeInfoPropertyName = \"{typeInfoPropName}{interfaceName}\")]");
        }
    }
}
