using System.Collections.Generic;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class ParametersEmitter
{
    private const string ClientCoreNamespace = "global::BlueBlaze.Core";

    internal static void Emit(
        string[] segments,
        ParametersDefinition paramsDef,
        string? generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var modelPath = string.Join(".", segments);
        const string ClassName = "Parameters";
        var classPath = modelPath + "." + ClassName;

        var isb = new IndentedStringBuilder();
        isb.AppendLine("// <auto-generated/>");
        isb.AppendLine("#nullable enable");
        isb.AppendLine("#pragma warning disable CS1591");
        isb.AppendLine();
        if (!string.IsNullOrEmpty(generatedCodeNamespace))
        {
            isb.AppendLine($"namespace {generatedCodeNamespace};");
            isb.AppendLine();
        }

        OpenSealedContainers(isb, segments);

        isb.AppendLine($"public sealed partial class {ClassName} : {ClientCoreNamespace}.ILexiconParameters");
        isb.AppendLine("{");
        using (isb.Indent())
        {
            isb.AppendLine("public global::System.Collections.Generic.IReadOnlyDictionary<string, string[]> ToDictionary()");
            isb.AppendLine("{");
            using (isb.Indent())
            {
                isb.AppendLine("var dict = new global::System.Collections.Generic.Dictionary<string, string[]>();");

                var requiredSet = new HashSet<string>(paramsDef.Required ?? []);
                if (paramsDef.Properties != null)
                {
                    foreach (var kv in paramsDef.Properties)
                    {
                        var propName = kv.Key;
                        var isRequired = requiredSet.Contains(propName);

                        var csPropName = LexiconNameHelper.ToPascalCase(propName);
                        if (csPropName == "Parameters")
                        {
                            csPropName += "Value";
                        }

                        EmitEntry(isb, propName, csPropName, kv.Value, isRequired);
                    }
                }

                isb.AppendLine("return dict;");
            }
            isb.AppendLine("}");
        }
        isb.AppendLine("}");

        CloseContainers(isb, segments.Length);

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, classPath + ".ILexiconParameters") + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, isb.ToString()));
    }

    private static void EmitEntry(
        IndentedStringBuilder isb,
        string jsonKey,
        string csPropName,
        LexiconDefinition def,
        bool isRequired)
    {
        if (def is ArrayDefinition arrDef)
        {
            var selector = GetArrayItemSelector("x", arrDef.Items);
            if (isRequired)
            {
                isb.AppendLine($"dict[\"{jsonKey}\"] = global::System.Linq.Enumerable.ToArray(");
                using (isb.Indent())
                {
                    isb.AppendLine($"global::System.Linq.Enumerable.Select(this.{csPropName}, x => {selector}));");
                }
            }
            else
            {
                isb.AppendLine($"if (this.{csPropName} != null)");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine($"dict[\"{jsonKey}\"] = global::System.Linq.Enumerable.ToArray(");
                    using (isb.Indent())
                    {
                        isb.AppendLine($"global::System.Linq.Enumerable.Select(this.{csPropName}, x => {selector}));");
                    }
                }
                isb.AppendLine("}");
            }
            return;
        }

        if (def is BooleanDefinition or IntegerDefinition)
        {
            if (isRequired)
            {
                isb.AppendLine($"dict[\"{jsonKey}\"] = [{ScalarToString($"this.{csPropName}", def)}];");
            }
            else
            {
                isb.AppendLine($"if (this.{csPropName}.HasValue)");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine($"dict[\"{jsonKey}\"] = [{ScalarToString($"this.{csPropName}.Value", def)}];");
                }
                isb.AppendLine("}");
            }
            return;
        }

        // string (全フォーマット統一)・その他の参照型
        if (isRequired)
        {
            isb.AppendLine($"dict[\"{jsonKey}\"] = [this.{csPropName}];");
        }
        else
        {
            isb.AppendLine($"if (this.{csPropName} != null)");
            isb.AppendLine("{");
            using (isb.Indent())
            {
                isb.AppendLine($"dict[\"{jsonKey}\"] = [this.{csPropName}];");
            }
            isb.AppendLine("}");
        }
    }

    private static string ScalarToString(string expr, LexiconDefinition def)
    {
        return def switch
        {
            BooleanDefinition => $"{expr} ? \"true\" : \"false\"",
            IntegerDefinition => $"{expr}.ToString(global::System.Globalization.CultureInfo.InvariantCulture)",
            _ => expr
        };
    }

    private static string GetArrayItemSelector(string varName, LexiconDefinition itemDef)
    {
        return itemDef switch
        {
            BooleanDefinition => $"{varName} ? \"true\" : \"false\"",
            IntegerDefinition => $"{varName}.ToString(global::System.Globalization.CultureInfo.InvariantCulture)",
            _ => varName
        };
    }

    private static void OpenSealedContainers(IndentedStringBuilder isb, string[] segments)
    {
        for (var i = 0; i < segments.Length; i++)
        {
            isb.AppendLine($"public sealed partial class {segments[i]}");
            isb.AppendLine("{");
            isb.Indent();
        }
    }

    private static void CloseContainers(IndentedStringBuilder isb, int count)
    {
        for (var i = count - 1; i >= 0; i--)
        {
            isb.Dedent();
            isb.AppendLine("}");
        }
    }
}
