using System.Collections.Generic;
using System.Text;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class ParametersEmitter
{
    private const string ClientCoreNamespace = "global::BlueBlaze.Client.Core";

    internal static void Emit(
        string[] segments,
        ParametersDefinition paramsDef,
        string? generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var modelPath = string.Join(".", segments);
        const string ClassName = "Parameters";
        var classPath = modelPath + "." + ClassName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(generatedCodeNamespace))
        {
            sb.AppendLine($"namespace {generatedCodeNamespace};");
            sb.AppendLine();
        }

        OpenSealedContainers(sb, segments);

        var indent = new string(' ', segments.Length * 4);
        var indent1 = new string(' ', (segments.Length + 1) * 4);
        var indent2 = new string(' ', (segments.Length + 2) * 4);

        sb.AppendLine($"{indent}public sealed partial class {ClassName} : {ClientCoreNamespace}.ILexiconParameters");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent1}public global::System.Collections.Generic.IReadOnlyDictionary<string, string[]> ToDictionary()");
        sb.AppendLine($"{indent1}{{");
        sb.AppendLine($"{indent2}var dict = new global::System.Collections.Generic.Dictionary<string, string[]>();");

        var requiredSet = new HashSet<string>(paramsDef.Required ?? []);
        if (paramsDef.Properties != null)
        {
            foreach (var kv in paramsDef.Properties)
            {
                var propName = kv.Key;
                var csPropName = LexiconNameHelper.ToPascalCase(propName);
                var isRequired = requiredSet.Contains(propName);
                EmitEntry(sb, propName, csPropName, kv.Value, isRequired, indent2);
            }
        }

        sb.AppendLine($"{indent2}return dict;");
        sb.AppendLine($"{indent1}}}");
        sb.AppendLine($"{indent}}}");

        CloseContainers(sb, segments.Length);

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, classPath + ".ILexiconParameters") + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, sb.ToString()));
    }

    private static void EmitEntry(
        StringBuilder sb,
        string jsonKey,
        string csPropName,
        LexiconDefinition def,
        bool isRequired,
        string indent)
    {
        var inner = indent + "    ";

        if (def is ArrayDefinition arrDef)
        {
            var selector = GetArrayItemSelector("x", arrDef.Items);
            if (isRequired)
            {
                sb.AppendLine($"{indent}dict[\"{jsonKey}\"] = global::System.Linq.Enumerable.ToArray(");
                sb.AppendLine($"{indent}    global::System.Linq.Enumerable.Select(this.{csPropName}, x => {selector}));");
            }
            else
            {
                sb.AppendLine($"{indent}if (this.{csPropName} != null)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{inner}dict[\"{jsonKey}\"] = global::System.Linq.Enumerable.ToArray(");
                sb.AppendLine($"{inner}    global::System.Linq.Enumerable.Select(this.{csPropName}, x => {selector}));");
                sb.AppendLine($"{indent}}}");
            }
            return;
        }

        if (def is BooleanDefinition or IntegerDefinition)
        {
            if (isRequired)
            {
                sb.AppendLine($"{indent}dict[\"{jsonKey}\"] = [{ScalarToString($"this.{csPropName}", def)}];");
            }
            else
            {
                sb.AppendLine($"{indent}if (this.{csPropName}.HasValue)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{inner}dict[\"{jsonKey}\"] = [{ScalarToString($"this.{csPropName}.Value", def)}];");
                sb.AppendLine($"{indent}}}");
            }
            return;
        }

        // DateTimeOffset (datetime format) — value type, requires .HasValue
        if (def is StringDefinition { Format: StringFormat.DateTime })
        {
            const string FmtExpr = ".ToString(\"O\", global::System.Globalization.CultureInfo.InvariantCulture)";
            if (isRequired)
            {
                sb.AppendLine($"{indent}dict[\"{jsonKey}\"] = [this.{csPropName}{FmtExpr}];");
            }
            else
            {
                sb.AppendLine($"{indent}if (this.{csPropName}.HasValue)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{inner}dict[\"{jsonKey}\"] = [this.{csPropName}.Value{FmtExpr}];");
                sb.AppendLine($"{indent}}}");
            }
            return;
        }

        // Uri and other reference string types — use ToString() or direct
        var toStringExpr = def is StringDefinition { Format: StringFormat.Uri } ? ".ToString()" : "";
        if (isRequired)
        {
            sb.AppendLine($"{indent}dict[\"{jsonKey}\"] = [this.{csPropName}{toStringExpr}];");
        }
        else
        {
            sb.AppendLine($"{indent}if (this.{csPropName} != null)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{inner}dict[\"{jsonKey}\"] = [this.{csPropName}{toStringExpr}];");
            sb.AppendLine($"{indent}}}");
        }
    }

    private static string ScalarToString(string expr, LexiconDefinition def)
    {
        return def switch
        {
            BooleanDefinition => $"{expr} ? \"true\" : \"false\"",
            IntegerDefinition => $"{expr}.ToString(global::System.Globalization.CultureInfo.InvariantCulture)",
            _ => expr
        };
    }

    private static string GetArrayItemSelector(string varName, LexiconDefinition itemDef)
    {
        return itemDef switch
        {
            BooleanDefinition => $"{varName} ? \"true\" : \"false\"",
            IntegerDefinition => $"{varName}.ToString(global::System.Globalization.CultureInfo.InvariantCulture)",
            StringDefinition { Format: StringFormat.DateTime } =>
                $"{varName}.ToString(\"O\", global::System.Globalization.CultureInfo.InvariantCulture)",
            StringDefinition { Format: StringFormat.Uri } => $"{varName}.ToString()",
            _ => varName
        };
    }

    private static void OpenSealedContainers(StringBuilder sb, string[] segments)
    {
        for (var i = 0; i < segments.Length; i++)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}public sealed partial class {segments[i]}");
            sb.AppendLine($"{indent}{{");
        }
    }

    private static void CloseContainers(StringBuilder sb, int count)
    {
        for (var i = count - 1; i >= 0; i--)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }
    }
}
