using System.Collections.Generic;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class RequestEmitter
{
    private const string ClientCoreNamespace = "global::BlueBlaze.Core";

    internal static void Emit(
        string nsid,
        string[] segments,
        bool isQuery,
        bool hasParameters,
        bool hasInput,
        string? generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var modelPath = string.Join(".", segments);
        const string ClassName = "Request";
        var classPath = modelPath + "." + ClassName;

        var isb = new IndentedStringBuilder();
        isb.AppendLine("// <auto-generated/>");
        isb.AppendLine("#nullable enable");
        isb.AppendLine("#pragma warning disable CS1591");
        isb.AppendLine();
        if (!string.IsNullOrEmpty(generatedCodeNamespace))
        {
            isb.AppendLine($"namespace {generatedCodeNamespace};");
            isb.AppendLine();
        }

        OpenSealedContainers(isb, segments);

        var kindExpr = isQuery
            ? $"{ClientCoreNamespace}.LexiconOperationKind.Query"
            : $"{ClientCoreNamespace}.LexiconOperationKind.Procedure";

        var interfaceName = isQuery
            ? $"{ClientCoreNamespace}.IQueryRequest"
            : $"{ClientCoreNamespace}.IProcedureRequest";

        isb.AppendLine($"[{ClientCoreNamespace}.Lexicon(\"{nsid}\", {kindExpr})]");
        isb.AppendLine($"public sealed class {ClassName} : {interfaceName}");
        isb.AppendLine("{");
        using (isb.Indent())
        {
            // Constructor / singleton
            if (hasInput)
            {
                var inputType = GlobalType(generatedCodeNamespace, modelPath + ".Input");
                isb.AppendLine($"public {ClassName}({inputType} input)");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine("this.Input = input;");
                }
                isb.AppendLine("}");
                isb.AppendLine();
            }
            else if (hasParameters)
            {
                var paramsType = GlobalType(generatedCodeNamespace, modelPath + ".Parameters");
                isb.AppendLine($"public {ClassName}({paramsType}? parameters = null)");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine("this.Parameters = parameters;");
                }
                isb.AppendLine("}");
                isb.AppendLine();
            }
            else
            {
                isb.AppendLine($"public static readonly {ClassName} Instance = new();");
                isb.AppendLine();
                isb.AppendLine($"private {ClassName}() {{ }}");
                isb.AppendLine();
            }

            isb.AppendLine($"public string Nsid => \"{nsid}\";");

            if (isQuery)
            {
                if (hasParameters)
                {
                    isb.AppendLine($"public {ClientCoreNamespace}.ILexiconParameters? Parameters {{ get; }}");
                }
                else
                {
                    isb.AppendLine($"public {ClientCoreNamespace}.ILexiconParameters? Parameters => null;");
                }
            }
            else
            {
                if (hasInput)
                {
                    isb.AppendLine($"public {ClientCoreNamespace}.ILexiconInput? Input {{ get; }}");
                }
                else
                {
                    isb.AppendLine($"public {ClientCoreNamespace}.ILexiconInput? Input => null;");
                }
            }
        }
        isb.AppendLine("}");

        CloseContainers(isb, segments.Length);

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, classPath) + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, isb.ToString()));
    }

    private static string GlobalType(string? ns, string typePath)
    {
        return string.IsNullOrEmpty(ns) ? $"global::{typePath}" : $"global::{ns}.{typePath}";
    }

    private static void OpenSealedContainers(IndentedStringBuilder isb, string[] segments)
    {
        for (var i = 0; i < segments.Length; i++)
        {
            isb.AppendLine($"public sealed partial class {segments[i]}");
            isb.AppendLine("{");
            isb.Indent();
        }
    }

    private static void CloseContainers(IndentedStringBuilder isb, int count)
    {
        for (var i = count - 1; i >= 0; i--)
        {
            isb.Dedent();
            isb.AppendLine("}");
        }
    }
}
