using System.Collections.Generic;
using System.Text;

namespace BlueBlaze.LexiconGenerator.Core.Generation;

internal static class RequestEmitter
{
    private const string ClientCoreNamespace = "global::BlueBlaze.Client.Core";

    internal static void Emit(
        string nsid,
        string[] segments,
        bool isQuery,
        bool hasParameters,
        bool hasInput,
        string? generatedCodeNamespace,
        List<GeneratedSourceFile> files)
    {
        var modelPath = string.Join(".", segments);
        const string ClassName = "Request";
        var classPath = modelPath + "." + ClassName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(generatedCodeNamespace))
        {
            sb.AppendLine($"namespace {generatedCodeNamespace};");
            sb.AppendLine();
        }

        OpenSealedContainers(sb, segments);

        var indent = new string(' ', segments.Length * 4);
        var indent1 = new string(' ', (segments.Length + 1) * 4);

        sb.AppendLine($"{indent}public sealed class {ClassName} : {ClientCoreNamespace}.ILexiconRequest");
        sb.AppendLine($"{indent}{{");

        var methodExpr = isQuery
            ? "global::System.Net.Http.HttpMethod.Get"
            : "global::System.Net.Http.HttpMethod.Post";

        // Constructor / singleton
        if (hasInput)
        {
            var inputType = GlobalType(generatedCodeNamespace, modelPath + ".Input");
            sb.AppendLine($"{indent1}public {ClassName}({inputType} input)");
            sb.AppendLine($"{indent1}{{");
            sb.AppendLine($"{indent1}    this.Input = input;");
            sb.AppendLine($"{indent1}}}");
            sb.AppendLine();
        }
        else if (hasParameters)
        {
            var paramsType = GlobalType(generatedCodeNamespace, modelPath + ".Parameters");
            sb.AppendLine($"{indent1}public {ClassName}({paramsType}? parameters = null)");
            sb.AppendLine($"{indent1}{{");
            sb.AppendLine($"{indent1}    this.Parameters = parameters;");
            sb.AppendLine($"{indent1}}}");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine($"{indent1}public static readonly {ClassName} Instance = new();");
            sb.AppendLine();
            sb.AppendLine($"{indent1}private {ClassName}() {{ }}");
            sb.AppendLine();
        }

        sb.AppendLine($"{indent1}public string Nsid => \"{nsid}\";");
        sb.AppendLine($"{indent1}public global::System.Net.Http.HttpMethod Method => {methodExpr};");

        if (hasParameters)
        {
            sb.AppendLine($"{indent1}public {ClientCoreNamespace}.ILexiconParameters? Parameters {{ get; }}");
        }
        else
        {
            sb.AppendLine($"{indent1}public {ClientCoreNamespace}.ILexiconParameters? Parameters => null;");
        }

        if (hasInput)
        {
            sb.AppendLine($"{indent1}public {ClientCoreNamespace}.ILexiconInput? Input {{ get; }}");
        }
        else
        {
            sb.AppendLine($"{indent1}public {ClientCoreNamespace}.ILexiconInput? Input => null;");
        }

        sb.AppendLine($"{indent}}}");

        CloseContainers(sb, segments.Length);

        var hintName = LexiconNameHelper.GetHintNameBase(generatedCodeNamespace, classPath) + ".g.cs";
        files.Add(new GeneratedSourceFile(hintName, sb.ToString()));
    }

    private static string GlobalType(string? ns, string typePath)
    {
        return string.IsNullOrEmpty(ns) ? $"global::{typePath}" : $"global::{ns}.{typePath}";
    }

    private static void OpenSealedContainers(StringBuilder sb, string[] segments)
    {
        for (var i = 0; i < segments.Length; i++)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}public sealed partial class {segments[i]}");
            sb.AppendLine($"{indent}{{");
        }
    }

    private static void CloseContainers(StringBuilder sb, int count)
    {
        for (var i = count - 1; i >= 0; i--)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }
    }
}
