name: blueblaze

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    init: true

  pds:
    image: ghcr.io/bluesky-social/pds:latest@sha256:871194d23acfca3acac084aca2973860c4a4defa1437ecf0fe9fc45d2324702f
    profiles:
      - pds
    env_file:
      - pds.env
    volumes:
      - pds-data:/pds
    ports:
      - "3000:3000"
    restart: "no"

volumes:
  pds-data:
