name: blueblaze

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    init: true

  pds:
    image: ghcr.io/bluesky-social/pds:latest@sha256:1fa8bbceabb65d8e1710749b1ea92c1c20a7489ca38da4a0a5f64c0c10a70c29
    profiles:
      - pds
    env_file:
      - pds.env
    volumes:
      - pds-data:/pds
    ports:
      - "3000:3000"
    restart: "no"

volumes:
  pds-data:
