using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace BlueBlaze.ResxSourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ResxGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor ErrorDescriptor = new(
        id: "BBRS0001",
        title: "Resx source generation error",
        messageFormat: "{0}",
        category: "ResxSourceGenerator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor WarningDescriptor = new(
        id: "BBRS0002",
        title: "Resx source generation warning",
        messageFormat: "{0}",
        category: "ResxSourceGenerator",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private readonly record struct ResxFile(
        string FilePath,
        string? Content,
        string RootNamespace,
        string AccessModifier,
        bool GenerateLocalizableResourceString);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rootNamespaceProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns ?? string.Empty;
            });

        var resxFilesProvider = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith(".resx", StringComparison.OrdinalIgnoreCase))
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Where(static pair =>
            {
                var (additionalText, optionsProvider) = pair;
                var options = optionsProvider.GetOptions(additionalText);
                return !options.TryGetValue("build_metadata.EmbeddedResource.GenerateSource", out var v)
                    || !string.Equals(v, "false", StringComparison.OrdinalIgnoreCase);
            })
            .Combine(rootNamespaceProvider)
            .Select(static (pair, cancellationToken) =>
            {
                var ((additionalText, optionsProvider), rootNamespace) = pair;
                var options = optionsProvider.GetOptions(additionalText);
                options.TryGetValue("build_metadata.EmbeddedResource.AccessModifier", out var accessModifier);
                options.TryGetValue("build_metadata.EmbeddedResource.GenerateRoslynLocalizableResourceString", out var generateLocalizableStr);
                var content = additionalText.GetText(cancellationToken)?.ToString();
                return new ResxFile(
                    additionalText.Path,
                    content,
                    rootNamespace,
                    string.IsNullOrEmpty(accessModifier) ? "internal" : accessModifier!,
                    string.Equals(generateLocalizableStr, "true", StringComparison.OrdinalIgnoreCase));
            });

        context.RegisterSourceOutput(resxFilesProvider, static (spc, item) =>
        {
            if (item.Content is null)
            {
                spc.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic.Create(
                    WarningDescriptor,
                    Location.None,
                    $"Could not read .resx file: {item.FilePath}"));
                return;
            }

            try
            {
                var (hintName, source) = GenerateSource(item.FilePath, item.Content, item.RootNamespace, item.AccessModifier, item.GenerateLocalizableResourceString);
                spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            }
            catch (System.Xml.XmlException ex)
            {
                spc.ReportDiagnostic(Microsoft.CodeAnalysis.Diagnostic.Create(
                    ErrorDescriptor,
                    Location.None,
                    $"Failed to parse .resx file {item.FilePath}: {ex.Message}"));
            }
        });
    }

    private static (string HintName, string Source) GenerateSource(
        string filePath,
        string content,
        string rootNamespace,
        string accessModifier,
        bool generateLocalizableResourceString)
    {
        var fileName = Path.GetFileNameWithoutExtension(filePath);
        var className = SanitizeIdentifier(fileName);
        var resourceBaseName = string.IsNullOrEmpty(rootNamespace)
            ? className
            : rootNamespace + "." + className;

        var entries = ParseResxEntries(content);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CA1304");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(rootNamespace))
        {
            sb.AppendLine("namespace " + rootNamespace + ";");
            sb.AppendLine();
        }

        sb.AppendLine(accessModifier + " static partial class " + className);
        sb.AppendLine("{");
        sb.AppendLine("    private static global::System.Resources.ResourceManager? s_resourceManager;");
        sb.AppendLine();
        sb.AppendLine("    " + accessModifier + " static global::System.Resources.ResourceManager ResourceManager =>");
        sb.AppendLine("        s_resourceManager ??= new global::System.Resources.ResourceManager(");
        sb.AppendLine("            \"" + resourceBaseName + "\",");
        sb.AppendLine("            typeof(" + className + ").Assembly);");

        foreach (var (name, value) in entries)
        {
            var identifier = SanitizeIdentifier(name);
            var formatArgCount = CountFormatArgs(value);

            sb.AppendLine();

            if (generateLocalizableResourceString)
            {
                AppendLocalizableResourceStringMember(sb, accessModifier, identifier, name, className, formatArgCount);
            }
            else
            {
                AppendStringMember(sb, accessModifier, identifier, name, formatArgCount);
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.Append("#pragma warning restore CA1304");

        return (className + ".g.cs", sb.ToString());
    }

    private static void AppendStringMember(
        StringBuilder sb,
        string accessModifier,
        string identifier,
        string name,
        int formatArgCount)
    {
        if (formatArgCount > 0)
        {
            sb.AppendLine("    private static string " + identifier + " =>");
            sb.AppendLine("        ResourceManager.GetString(\"" + name + "\", null)!;");
            sb.AppendLine();

            sb.Append("    " + accessModifier + " static string Format" + identifier + "(");
            for (var i = 0; i < formatArgCount; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }

                sb.Append("object? arg" + i.ToString(System.Globalization.CultureInfo.InvariantCulture));
            }

            sb.AppendLine(")");
            sb.Append("        => string.Format(global::System.Globalization.CultureInfo.InvariantCulture, " + identifier);
            for (var i = 0; i < formatArgCount; i++)
            {
                sb.Append(", arg" + i.ToString(System.Globalization.CultureInfo.InvariantCulture));
            }

            sb.AppendLine(");");
        }
        else
        {
            sb.AppendLine("    " + accessModifier + " static string " + identifier + " =>");
            sb.AppendLine("        ResourceManager.GetString(\"" + name + "\", null)!;");
        }
    }

    private static void AppendLocalizableResourceStringMember(
        StringBuilder sb,
        string accessModifier,
        string identifier,
        string name,
        string className,
        int formatArgCount)
    {
        sb.AppendLine("    " + accessModifier + " static global::Microsoft.CodeAnalysis.LocalizableResourceString " + identifier + " =>");
        sb.AppendLine("        new global::Microsoft.CodeAnalysis.LocalizableResourceString(");
        sb.AppendLine("            \"" + name + "\",");
        sb.AppendLine("            ResourceManager,");
        sb.AppendLine("            typeof(" + className + "));");

        if (formatArgCount > 0)
        {
            sb.AppendLine();
            sb.Append("    " + accessModifier + " static global::Microsoft.CodeAnalysis.LocalizableResourceString Format" + identifier + "(");
            for (var i = 0; i < formatArgCount; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }

                sb.Append("string arg" + i.ToString(System.Globalization.CultureInfo.InvariantCulture));
            }

            sb.AppendLine(")");
            sb.AppendLine("        => new global::Microsoft.CodeAnalysis.LocalizableResourceString(");
            sb.AppendLine("            \"" + name + "\",");
            sb.AppendLine("            ResourceManager,");
            sb.Append("            typeof(" + className + ")");
            for (var i = 0; i < formatArgCount; i++)
            {
                sb.Append(", arg" + i.ToString(System.Globalization.CultureInfo.InvariantCulture));
            }

            sb.AppendLine(");");
        }
    }

    private static List<(string Name, string Value)> ParseResxEntries(string content)
    {
        var doc = XDocument.Parse(content);
        var result = new List<(string, string)>();

        if (doc.Root is null)
        {
            return result;
        }

        foreach (var element in doc.Root.Elements("data"))
        {
            if (element.Attribute("type") != null)
            {
                continue;
            }

            var name = element.Attribute("name")?.Value;
            if (name is null)
            {
                continue;
            }

            var value = element.Element("value")?.Value ?? string.Empty;
            result.Add((name, value));
        }

        return result;
    }

    private static int CountFormatArgs(string value)
    {
        var max = -1;
        var i = 0;
        while (i < value.Length)
        {
            if (value[i] == '{' && i + 1 < value.Length)
            {
                if (value[i + 1] == '{')
                {
                    i += 2;
                    continue;
                }

                var j = i + 1;
                while (j < value.Length && char.IsDigit(value[j]))
                {
                    j++;
                }

                if (j > i + 1)
                {
                    var indexStr = value.Substring(i + 1, j - i - 1);
                    if (int.TryParse(
                            indexStr,
                            System.Globalization.NumberStyles.Integer,
                            System.Globalization.CultureInfo.InvariantCulture,
                            out var index) &&
                        index > max)
                    {
                        max = index;
                    }
                }
            }

            i++;
        }

        return max + 1;
    }

    private static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "_";
        }

        var sb = new StringBuilder(name.Length);
        for (var i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (i == 0)
            {
                sb.Append(char.IsLetter(c) || c == '_' ? c : '_');
            }
            else
            {
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            }
        }

        return sb.ToString();
    }
}
