using System.Collections.Generic;
using System.Linq;

using Microsoft.CodeAnalysis;

namespace BlueBlaze.CommandGenerator.Generation;

/// <summary>
/// 1つの NSID(<see cref="LexiconRequestInfo"/>)に対する CLI コマンド構築コードを生成する。
/// 生成されるコードは <c>{ContainerSegments}CliCommand.BuildCliCommand(IAtProtocolClient client)</c>
/// という静的メソッドで、System.CommandLine の <c>Command</c> を1つ返す。
/// </summary>
internal static class CliCommandEmitter
{
    private const string CommandLineNs = "global::System.CommandLine";
    private const string CoreNs = "global::BlueBlaze.Core";
    private const string CliOutputType = "global::BlueBlaze.Application.Cli.CliOutput";
    private const string CliInputReaderType = "global::BlueBlaze.Application.Cli.CliInputReader";

    internal static string CommandClassName(string[] segments)
    {
        return string.Concat(segments) + "CliCommand";
    }

    internal static string Emit(
        LexiconRequestInfo request,
        CliEligibilityResult eligibility,
        string[] segments,
        string generatedNamespace,
        INamedTypeSymbol? jsonSerializerContextType)
    {
        var commandClassName = CommandClassName(segments);

        var isb = new IndentedStringBuilder();
        isb.AppendLine("// <auto-generated/>");
        isb.AppendLine("#nullable enable");
        isb.AppendLine();
        isb.AppendLine($"namespace {generatedNamespace};");
        isb.AppendLine();
        isb.AppendLine($"internal static class {commandClassName}");
        isb.AppendLine("{");
        using (isb.Indent())
        {
            EmitBuildMethod(isb, request, eligibility, segments, jsonSerializerContextType);
        }
        isb.AppendLine("}");

        return isb.ToString();
    }

    private static void EmitBuildMethod(
        IndentedStringBuilder isb,
        LexiconRequestInfo request,
        CliEligibilityResult eligibility,
        string[] segments,
        INamedTypeSymbol? jsonSerializerContextType)
    {
        var leafKebabName = NameHelper.ToKebabCase(segments[segments.Length - 1]);

        isb.AppendLine($"internal static {CommandLineNs}.Command BuildCliCommand({CoreNs}.IAtProtocolClient client)");
        isb.AppendLine("{");
        using (isb.Indent())
        {
            isb.AppendLine($"var command = new {CommandLineNs}.Command(\"{leafKebabName}\", \"{request.Nsid}\");");
            isb.AppendLine();

            var parameterOptions = EmitOptionDeclarations(isb, eligibility.ParameterProperties, "Option");

            var inputPrimitives = eligibility.InputProperties?.Where(p => p.IsPrimitive).ToList() ?? [];
            var inputOptions = EmitOptionDeclarations(isb, inputPrimitives, "Option");

            string? inputJsonVarName = null;
            if (eligibility.NeedsInputJsonFallback)
            {
                inputJsonVarName = "inputJsonOption";
                isb.AppendLine($"var {inputJsonVarName} = new {CommandLineNs}.Option<string?>(\"--input-json\");");
            }

            isb.AppendLine();
            foreach (var varName in parameterOptions.Values.Concat(inputOptions.Values))
            {
                isb.AppendLine($"command.Add({varName});");
            }

            if (inputJsonVarName is not null)
            {
                isb.AppendLine($"command.Add({inputJsonVarName});");
            }

            isb.AppendLine();
            isb.AppendLine($"command.SetAction(async ({CommandLineNs}.ParseResult parseResult, global::System.Threading.CancellationToken cancellationToken) =>");
            isb.AppendLine("{");
            using (isb.Indent())
            {
                isb.AppendLine("try");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    EmitHandlerBody(isb, request, eligibility, parameterOptions, inputOptions, inputJsonVarName, jsonSerializerContextType);
                }
                isb.AppendLine("}");
                isb.AppendLine($"catch ({CoreNs}.LexiconException ex)");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine($"{CliOutputType}.WriteError(ex);");
                    isb.AppendLine("return 1;");
                }
                isb.AppendLine("}");
            }
            isb.AppendLine("});");
            isb.AppendLine();
            isb.AppendLine("return command;");
        }
        isb.AppendLine("}");
    }

    // 各プロパティに対応する Option<T> 変数の宣言を出力し、(プロパティ -> 変数名) の対応を返す。
    private static Dictionary<LexiconPropertyInfo, string> EmitOptionDeclarations(
        IndentedStringBuilder isb,
        List<LexiconPropertyInfo> properties,
        string suffix)
    {
        var result = new Dictionary<LexiconPropertyInfo, string>();

        foreach (var prop in properties)
        {
            var varName = ToCamelCase(prop.CSharpName) + suffix;
            var optionType = BuildOptionType(prop);
            var kebabName = NameHelper.ToKebabCase(prop.JsonName);

            isb.AppendLine($"var {varName} = new {CommandLineNs}.Option<{optionType}>(\"--{kebabName}\")");
            if (prop.IsRequired)
            {
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine("Required = true,");
                }
                isb.AppendLine("};");
            }
            else
            {
                isb.AppendLine(";");
            }

            result[prop] = varName;
        }

        return result;
    }

    private static void EmitHandlerBody(
        IndentedStringBuilder isb,
        LexiconRequestInfo request,
        CliEligibilityResult eligibility,
        Dictionary<LexiconPropertyInfo, string> parameterOptions,
        Dictionary<LexiconPropertyInfo, string> inputOptions,
        string? inputJsonVarName,
        INamedTypeSymbol? jsonSerializerContextType)
    {
        string? parametersArg = null;
        if (request.ParametersType is not null)
        {
            parametersArg = "parameters";
            EmitObjectConstruction(isb, "parameters", request.ParametersType, eligibility.ParameterProperties, parameterOptions);
        }

        string? inputArg = null;
        if (request.InputType is not null)
        {
            inputArg = "input";
            var inputFullName = request.InputType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (inputJsonVarName is not null)
            {
                isb.AppendLine($"var inputJsonValue = parseResult.GetValue({inputJsonVarName});");
                isb.AppendLine($"{inputFullName} input;");
                isb.AppendLine("if (inputJsonValue is not null)");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    isb.AppendLine($"var resolvedJson = await {CliInputReaderType}.ReadInputJsonAsync(inputJsonValue, cancellationToken).ConfigureAwait(false);");
                    var deserializeExpr = BuildDeserializeExpression(inputFullName, request.InputType, jsonSerializerContextType);
                    isb.AppendLine($"input = {deserializeExpr}");
                    using (isb.Indent())
                    {
                        isb.AppendLine("?? throw new global::System.InvalidOperationException(\"--input-json の内容を解釈できませんでした。\");");
                    }
                }
                isb.AppendLine("}");
                isb.AppendLine("else");
                isb.AppendLine("{");
                using (isb.Indent())
                {
                    EmitObjectConstruction(isb, "input", request.InputType, eligibility.InputProperties ?? [], inputOptions, onlyPrimitive: true, declareAsVar: false);
                }
                isb.AppendLine("}");
            }
            else
            {
                EmitObjectConstruction(isb, "input", request.InputType, eligibility.InputProperties ?? [], inputOptions);
            }
        }

        // {Operation}Async 拡張メソッド(Output型固定の Deserializer を内部で使う)は経由しない。
        // Request インスタンスを自分で構築し、IAtProtocolClient.SendAsync に
        // RawJsonDeserializer を直接渡す。これにより「デシリアライズ→再シリアライズ」という
        // 無駄な往復(NativeAOT 非互換なリフレクションシリアライズの原因)を避けられる。
        var requestFullName = request.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var requestExpr = (parametersArg, inputArg) switch
        {
            (not null, _) => $"new {requestFullName}({parametersArg})",
            (_, not null) => $"new {requestFullName}({inputArg})",
            _ => $"{requestFullName}.Instance",
        };

        isb.AppendLine($"var response = await client.SendAsync({requestExpr}, {CoreNs}.RawJsonDeserializer.Instance, cancellationToken).ConfigureAwait(false);");
        isb.AppendLine($"{CliOutputType}.WriteJson(response.Output);");
        isb.AppendLine("return 0;");
    }

    // 必須プロパティを名前付き引数でコンストラクタに渡し、省略可能プロパティを後から設定するコードを出力する。
    private static void EmitObjectConstruction(
        IndentedStringBuilder isb,
        string varName,
        INamedTypeSymbol type,
        List<LexiconPropertyInfo> properties,
        Dictionary<LexiconPropertyInfo, string> optionVarNames,
        bool onlyPrimitive = false,
        bool declareAsVar = true)
    {
        var typeFullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var targetProperties = onlyPrimitive ? properties.Where(p => p.IsPrimitive).ToList() : properties;

        var requiredProps = targetProperties.Where(p => p.IsRequired).ToList();
        var optionalProps = targetProperties.Where(p => !p.IsRequired).ToList();

        foreach (var prop in requiredProps)
        {
            var optionVarName = optionVarNames[prop];
            isb.AppendLine($"var {ValueVarName(prop)} = parseResult.GetValue({optionVarName});");
        }

        foreach (var prop in optionalProps)
        {
            var optionVarName = optionVarNames[prop];
            isb.AppendLine($"var {ValueVarName(prop)} = parseResult.GetValue({optionVarName});");
        }

        // declareAsVar=false は --input-json フォールバックがある場合に使う。外側で
        // 既に `{typeFullName} {varName};` を宣言済みのため、ここでは代入のみ行う。
        var declPrefix = declareAsVar ? "var " : "";

        if (requiredProps.Count == 0)
        {
            isb.AppendLine($"{declPrefix}{varName} = new {typeFullName}();");
        }
        else
        {
            var argList = string.Join(", ", requiredProps.Select(p => $"{p.JsonName}: {ValueVarName(p)}!"));
            isb.AppendLine($"{declPrefix}{varName} = new {typeFullName}({argList});");
        }

        foreach (var prop in optionalProps)
        {
            isb.AppendLine($"if ({ValueVarName(prop)} is not null)");
            isb.AppendLine("{");
            using (isb.Indent())
            {
                // LexiconGenerator.Core は required ではない値型(bool/int)プロパティを
                // 明示的な default が無い限り T のまま生成する(T? にしない)。
                // Option<T> 側は常に T? なので、その場合は .Value で unwrap する。
                var assignExpr = prop.IsPropertyTypeNullable
                    ? ValueVarName(prop)
                    : $"{ValueVarName(prop)}.Value";
                isb.AppendLine($"{varName}.{prop.CSharpName} = {assignExpr};");
            }
            isb.AppendLine("}");
        }
    }

    private static string BuildDeserializeExpression(
        string inputFullName,
        INamedTypeSymbol inputType,
        INamedTypeSymbol? jsonSerializerContextType)
    {
        if (jsonSerializerContextType is not null)
        {
            var contextFqn = jsonSerializerContextType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var contextNs = jsonSerializerContextType.ContainingNamespace.ToDisplayString();
            var inputFqn = inputType.ToDisplayString();
            if (inputFqn.StartsWith(contextNs + ".", System.StringComparison.Ordinal))
            {
                var relative = inputFqn.Substring(contextNs.Length + 1);
                var typeInfoPropName = relative.Replace(".", "");
                return $"global::System.Text.Json.JsonSerializer.Deserialize(resolvedJson, {contextFqn}.Default.{typeInfoPropName})";
            }
        }

        return $"global::System.Text.Json.JsonSerializer.Deserialize<{inputFullName}>(resolvedJson)";
    }

    private static string ValueVarName(LexiconPropertyInfo prop)
    {
        return ToCamelCase(prop.CSharpName) + "Value";
    }

    private static string ToCamelCase(string pascalCase)
    {
        if (string.IsNullOrEmpty(pascalCase))
        {
            return pascalCase;
        }

        return char.ToLowerInvariant(pascalCase[0]) + pascalCase.Substring(1);
    }

    private static string BuildOptionType(LexiconPropertyInfo prop)
    {
        var baseType = prop.PrimitiveKind switch
        {
            LexiconPrimitiveKind.String => "string",
            LexiconPrimitiveKind.Int => "int",
            LexiconPrimitiveKind.Bool => "bool",
            _ => "string",
        };

        if (prop.IsArray)
        {
            baseType += "[]";
        }

        if (!prop.IsRequired)
        {
            baseType += "?";
        }

        return baseType;
    }
}
