using System;
using System.Collections.Generic;
using System.Linq;

namespace BlueBlaze.CommandGenerator.Generation;

/// <summary>
/// 対象内と判定された全 NSID の <c>BuildCliCommand</c> 呼び出しを、
/// NSID セグメントごとの中間 <c>Command</c> にぶら下げて1つの <c>RootCommand</c> を組み立てる
/// <c>CliCommandTree.BuildRootCommand</c> を生成する。
/// </summary>
internal static class CliCommandTreeEmitter
{
    internal static string Emit(
        List<(LexiconRequestInfo Request, string[] Segments)> eligibleRequests,
        string generatedNamespace)
    {
        var isb = new IndentedStringBuilder();
        isb.AppendLine("// <auto-generated/>");
        isb.AppendLine("#nullable enable");
        isb.AppendLine();
        isb.AppendLine($"namespace {generatedNamespace};");
        isb.AppendLine();
        isb.AppendLine("internal static class CliCommandTree");
        isb.AppendLine("{");
        using (isb.Indent())
        {
            isb.AppendLine("internal static global::System.CommandLine.RootCommand BuildRootCommand(global::BlueBlaze.Core.IAtProtocolClient client)");
            isb.AppendLine("{");
            using (isb.Indent())
            {
                isb.AppendLine("var root = new global::System.CommandLine.RootCommand(\"BlueBlaze AT Protocol XRPC CLI\");");
                isb.AppendLine();

                EmitTreeBody(isb, eligibleRequests);

                isb.AppendLine();
                isb.AppendLine("return root;");
            }
            isb.AppendLine("}");
        }
        isb.AppendLine("}");

        return isb.ToString();
    }

    private static void EmitTreeBody(
        IndentedStringBuilder isb,
        List<(LexiconRequestInfo Request, string[] Segments)> eligibleRequests)
    {
        // 同じ入力からは常に同じコードが生成されるよう、NSID のアルファベット順で処理する。
        var sorted = eligibleRequests
            .OrderBy(r => string.Join(".", r.Segments), StringComparer.Ordinal)
            .ToList();

        var nodeVarNames = new Dictionary<string, string>();

        foreach (var (request, segments) in sorted)
        {
            for (var depth = 1; depth < segments.Length; depth++)
            {
                var prefixKey = string.Join(".", segments, 0, depth);
                if (nodeVarNames.ContainsKey(prefixKey))
                {
                    continue;
                }

                var varName = ToCamelCase(string.Concat(segments.Take(depth)));
                nodeVarNames[prefixKey] = varName;

                var kebabName = NameHelper.ToKebabCase(segments[depth - 1]);
                isb.AppendLine($"var {varName} = new global::System.CommandLine.Command(\"{kebabName}\", \"{prefixKey}\");");

                if (depth == 1)
                {
                    isb.AppendLine($"root.Add({varName});");
                }
                else
                {
                    var parentKey = string.Join(".", segments, 0, depth - 1);
                    var parentVar = nodeVarNames[parentKey];
                    isb.AppendLine($"{parentVar}.Add({varName});");
                }
            }

            var leafCommandClass = CliCommandEmitter.CommandClassName(segments);
            var leafExpr = $"{leafCommandClass}.BuildCliCommand(client)";

            if (segments.Length == 1)
            {
                isb.AppendLine($"root.Add({leafExpr});");
            }
            else
            {
                var parentKey = string.Join(".", segments, 0, segments.Length - 1);
                var parentVar = nodeVarNames[parentKey];
                isb.AppendLine($"{parentVar}.Add({leafExpr});");
            }
        }
    }

    private static string ToCamelCase(string pascalCase)
    {
        if (string.IsNullOrEmpty(pascalCase))
        {
            return pascalCase;
        }

        return char.ToLowerInvariant(pascalCase[0]) + pascalCase.Substring(1);
    }
}
