name: Component Detection

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  dependency-submission:
    name: Dependency Submission
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Cache LexiconGenerator.Cli
        id: bbgen-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ runner.temp }}/bbgen
          key: bbgen_ubuntu-slim_${{ hashFiles('global.json', 'Directory.Build.props', 'Directory.Build.targets', 'Directory.Packages.props', 'BeforeMicrosoftNETSdkTargets.targets', 'Generators/LexiconGenerator/Cli/**', 'Generators/LexiconGenerator/Core/**') }}

      - name: Build LexiconGenerator.Cli
        if: steps.bbgen-cache.outputs.cache-hit != 'true'
        run: dotnet publish Generators/LexiconGenerator/Cli/LexiconGenerator.Cli.csproj -o "${{ runner.temp }}/bbgen"

      - name: Build
        run: >
          dotnet build
          --configuration Release
          --no-incremental
          --no-logo
          -p:BlueBlazeGeneratorCliExe="${{ runner.temp }}/bbgen/BlueBlaze.LexiconGenerator.Cli"
          -binaryLogger

      - name: Component Detection
        uses: advanced-security/component-detection-dependency-submission-action@31f25a8de68ae5ce2ca274bc28546a78683c15ce # v0.1.4
        with:
          detectorArgs: DockerReference=Enable,DockerCompose=Enable,MSBuildBinaryLog=EnableIfDefaultOff
          detectorsCategories: NuGet,Npm,DockerReference,DockerCompose
