name: CST

on:
  push:
    branches: [actions]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Create results directory
        run: mkdir -p analysis-results

      - uses: microsoft/DevSkim-Action@4b5047945a44163b94642a1cecc0d93a3f428cc6 # v1.0.16
        with:
          output-directory: analysis-results
          output-filename: devskim.sarif

      - uses: microsoft/ApplicationInspector-action@687538ee305a6bcd9379aa70ed03ec348ede6e09 # main
        with:
          output-format: sarif
          output-path: analysis-results/appinspector.sarif

      - uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: analysis-results
